name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Django Matera 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Check code style with Black
        run: poetry run black --check .

      - name: Check import order with isort
        run: poetry run isort . --check-only

      - name: Lint with Ruff
        run: poetry run ruff check .

      - name: Apply migrations
        run: poetry run python manage.py migrate

      - name: Check for uncommitted migrations
        run: poetry run python manage.py makemigrations --check --dry-run

      - name: Run tests with coverage
        run: |
          poetry run coverage run manage.py test
          poetry run coverage report
