# Generated by Django 5.2 on 2025-04-15 14:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "monthly_interest_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("requested_date", models.DateTimeField(auto_now_add=True)),
                ("bank", models.CharField(max_length=255)),
                ("client", models.CharField(max_length=255)),
                ("is_fully_paid", models.BooleanField(default=False)),
                (
                    "insurance_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.01"), max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
