# Generated by Django 5.2 on 2025-04-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='requested_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
